# Generated by Django 5.2.4 on 2025-08-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('food_img', models.CharField(blank=True, max_length=255, null=True)),
                ('food_name', models.CharField(max_length=255)),
                ('food_category', models.CharField(max_length=255)),
                ('representative_food', models.CharField(max_length=255)),
                ('nutritional_value_standard_amount', models.BigIntegerField()),
                ('calorie', models.BigIntegerField()),
                ('moisture', models.BigIntegerField()),
                ('protein', models.BigIntegerField()),
                ('fat', models.BigIntegerField()),
                ('carbohydrate', models.BigIntegerField()),
                ('sugar', models.BigIntegerField(blank=True, null=True)),
                ('dietary_fiber', models.BigIntegerField(blank=True, null=True)),
                ('calcium', models.BigIntegerField(blank=True, null=True)),
                ('iron_content', models.BigIntegerField(blank=True, null=True)),
                ('phosphorus', models.BigIntegerField(blank=True, null=True)),
                ('potassium', models.BigIntegerField(blank=True, null=True)),
                ('salt', models.BigIntegerField(blank=True, null=True)),
                ('VitaminA', models.BigIntegerField(blank=True, null=True)),
                ('VitaminB', models.BigIntegerField(blank=True, null=True)),
                ('VitaminC', models.BigIntegerField(blank=True, null=True)),
                ('VitaminD', models.BigIntegerField(blank=True, null=True)),
                ('VitaminE', models.BigIntegerField(blank=True, null=True)),
                ('cholesterol', models.BigIntegerField(blank=True, null=True)),
                ('saturated_fatty_acids', models.BigIntegerField(blank=True, null=True)),
                ('trans_fatty_acids', models.BigIntegerField(blank=True, null=True)),
                ('serving_size', models.BigIntegerField(blank=True, null=True)),
                ('weight', models.BigIntegerField()),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
    ]
