# Generated by Django 5.2.4 on 2025-08-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='crawled_at',
            field=models.DateTimeField(blank=True, help_text='크롤링 수행 시간', null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='crawling_error',
            field=models.TextField(blank=True, help_text='크롤링 오류 메시지', null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='crawling_status',
            field=models.CharField(choices=[('pending', '대기 중'), ('in_progress', '크롤링 중'), ('success', '성공'), ('failed', '실패'), ('not_found', '제품 없음')], default='pending', help_text='크롤링 상태', max_length=20),
        ),
        migrations.AddField(
            model_name='price',
            name='product_image_url',
            field=models.URLField(blank=True, help_text='크롤링된 제품 이미지 URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='product_url',
            field=models.URLField(blank=True, help_text='크롤링된 제품 상세 페이지 URL', max_length=500, null=True),
        ),
    ]
