# Generated by Django 5.2.4 on 2025-08-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calorie',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='nutrition_score',
            field=models.FloatField(blank=True, help_text='0-26 영양 점수', null=True),
        ),
    ]
