# Generated by Django 5.2.4 on 2025-08-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_calorie_alter_food_food_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='magnesium',
        ),
    ]
