# Generated by Django 5.2.4 on 2025-08-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_price_crawled_at_price_crawling_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.CharField(help_text='식품 고유 ID (예: P101-405000400-4180)', max_length=255, primary_key=True, serialize=False),
        ),
    ]
