<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-08-05 12:58
=======
# Generated by Django 5.2.4 on 2025-08-07 06:01
>>>>>>> b62ea9d7c06440f2a2e65720758f63238b02aef2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='VitaminA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='VitaminB',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='VitaminC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='VitaminD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='VitaminE',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='calcium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='calorie',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='cholesterol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='dietary_fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='iron_content',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='moisture',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='phosphorus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='salt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='saturated_fatty_acids',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='serving_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='trans_fatty_acids',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.FloatField(),
        ),
    ]
