# Generated by Django 5.2.4 on 2025-08-09 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_vitamina_alter_food_vitaminb_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteFood',
            fields=[
                ('favorite_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='foods.food')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Favorite_Food',
                'indexes': [models.Index(fields=['user', 'food'], name='Favorite_Fo_user_id_f9ffe5_idx')],
                'unique_together': {('user', 'food')},
            },
        ),
    ]
