# Generated by Django 5.2.4 on 2025-08-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_options_food_created_at_food_nrf_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='serving_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.FloatField(),
        ),
    ]
