# Generated by Django 5.2.4 on 2025-08-15 11:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_food_crawled_at_food_crawling_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='salt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
