# Generated by Django 5.2.4 on 2025-08-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_favoritefood'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='magnesium',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
