# Generated by Django 5.2.4 on 2025-08-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_food_food_id_alter_food_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='crawled_at',
        ),
        migrations.RemoveField(
            model_name='food',
            name='crawling_error',
        ),
        migrations.RemoveField(
            model_name='food',
            name='crawling_status',
        ),
        migrations.RemoveField(
            model_name='food',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='food',
            name='nrf_index',
        ),
        migrations.RemoveField(
            model_name='food',
            name='nutri_score_grade',
        ),
        migrations.RemoveField(
            model_name='food',
            name='nutrition_score',
        ),
        migrations.RemoveField(
            model_name='food',
            name='product_image_url',
        ),
        migrations.RemoveField(
            model_name='food',
            name='product_url',
        ),
        migrations.RemoveField(
            model_name='food',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='food',
            name='discount_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='shop_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
