# Generated by Django 5.2.4 on 2025-08-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_food_serving_size_alter_food_weight'),
        ('foods', '0005_food_magnesium'),
    ]

    operations = [
    ]
