# Generated by Django 5.2.4 on 2025-08-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_merge_20250813_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calorie',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='salt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
