# Generated by Django 5.2.4 on 2025-08-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_remove_food_crawled_at_remove_food_crawling_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='nrf_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='nutri_score_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='nutrition_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
