# Generated by Django 5.2.4 on 2025-08-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_food_nrf_index_food_nutri_score_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='price',
            new_name='lprice',
        ),
    ]
