# Generated by Django 5.2.4 on 2025-08-17 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_food_mallname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='shop_name',
        ),
    ]
