# Generated by Django 5.2.4 on 2025-08-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_remove_food_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='mallName',
        ),
    ]
