version: "3.8"

services:
  web:
    build: .
    container_name: healthtant_web
    restart: unless-stopped
    command: >
      sh -lc "gunicorn config.wsgi:application
               --bind 0.0.0.0:8000
               --workers 2 --timeout 120
               --max-requests 1000 --max-requests-jitter 50"
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.27-alpine
    container_name: healthtant_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web

  db:
    image: postgres:15
    container_name: healthtant_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: healthtant
      POSTGRES_USER: healthtant_user
      POSTGRES_PASSWORD: healthtant_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healthtant_user -d healthtant || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  static_volume:
  postgres_data: