version: "3.8"

services:
  web:
    image: ghcr.io/<OWNER>/<REPO>:latest
    container_name: healthtant_web
    restart: unless-stopped
    command: >
      sh -lc "gunicorn config.wsgi:application
               --bind 0.0.0.0:8000
               --workers 2 --timeout 120
               --max-requests 1000 --max-requests-jitter 50"
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - "8000"

  nginx:
    image: nginx:1.27-alpine
    container_name: healthtant_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web

volumes:
  static_volume: