# Generated by Django 5.2.4 on 2025-08-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_nickname_and_more'),
        ('accounts', '0002_alter_userprofile_options_userprofile_created_at_and_more'),
    ]

    operations = [
    ]
