# Generated by Django 5.2.4 on 2025-08-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_profile_image'),
        ('accounts', '0004_alter_userprofile_nickname'),
    ]

    operations = [
    ]
