# Generated by Django 5.2.4 on 2025-08-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20250813_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image_url',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
