# Generated by Django 5.2.4 on 2025-08-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_profile_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_image',
            new_name='profile_image_url',
        ),
    ]
