# Generated by Django 5.2.4 on 2025-08-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20250813_2347'),
        ('accounts', '0007_rename_profile_image_userprofile_profile_image_url'),
    ]

    operations = [
    ]
