# Generated by Django 5.2.4 on 2025-08-05 13:59

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
        ('foods', '0003_alter_food_options_food_created_at_food_nrf_index_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diet',
            options={'verbose_name': '식단', 'verbose_name_plural': '식단들'},
        ),
        migrations.AddField(
            model_name='diet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='diet_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diet',
            name='meal',
            field=models.CharField(choices=[('B', '아침'), ('L', '점심'), ('D', '저녁')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='diet',
            unique_together={('user', 'food', 'date', 'meal')},
        ),
        migrations.AlterModelTable(
            name='diet',
            table='diet',
        ),
    ]
