# Generated by Django 5.2.4 on 2025-08-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0002_alter_diet_meal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diet',
            unique_together=set(),
        ),
    ]
